services:
  - type: web
    name: dc-tecnologia-vendas
    runtime: docker
    healthCheckPath: /login
    autoDeploy: true
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_KEY
        generateValue: true
      - key: LOG_CHANNEL
        value: stderr
      - key: SESSION_DRIVER
        value: file
      - key: CACHE_STORE
        value: file
      - key: QUEUE_CONNECTION
        value: sync
      - key: RUN_MIGRATIONS
        value: "true"
      - key: RUN_SEEDER
        value: "false"
      - key: DB_CONNECTION
        value: pgsql
      - key: DATABASE_URL
        sync: false
